apiVersion: v1
kind: Service
metadata:
  name: petclinic-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: petclinic-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      nodePort: {{ .Values.backend.service.nodePort }}
