apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: angular-frontend
          image: {{ .Values.frontend.image }}
          env:
            - name: API_URL
              value: {{ .Values.frontend.env.API_URL | quote }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          volumeMounts:
            - name: local-persistent-storage
              mountPath: "/"
      volumes:
        - name: local-persistent-storage
          persistentVolumeClaim:
            claimName: ui-pvc
