apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
