apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-backend
  template:
    metadata:
      labels:
        app: petclinic-backend
    spec:
      containers:
        - name: backend
          image: kadhir22/petclinic-minikube:4
          ports:
            - containerPort: 9966
---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: petclinic-backend
spec:
  type: NodePort
  selector:
    app: petclinic-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9966
      nodePort: 32638
