# frontend.deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
      - name: angular-frontend
        image: kadhir22/angular-petclinic:4
        env:
        - name: API_URL
          value: "http://103.176.85.60:32638/petclinic/api/"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: NodePort  # Makes it accessible outside the cluster
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30089  # Exposes on port 30080
