frontend:
  image: kadhir22/angular-petclinic:4
  replicas: 1
  containerPort: 8080
  env:
    API_URL: "http://103.176.85.60:32638/petclinic/api/"
  service:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30089

backend:
  image: kadhir22/petclinic-minikube:4
  replicas: 1
  containerPort: 9966
  service:
    type: NodePort
    port: 8080
    targetPort: 9966
    nodePort: 32638
